CREATE TABLE public.app_settings (
                                     id integer NOT NULL,
                                     created_at timestamp(6) without time zone NOT NULL,
                                     updated_at timestamp(6) without time zone NOT NULL,
                                     module character varying(255) NOT NULL,
                                     setting character varying(255) NOT NULL,
                                     value character varying(255) NOT NULL
);

ALTER TABLE public.app_settings OWNER TO postgres;

ALTER TABLE public.app_settings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_settings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE SEQUENCE public.app_settings_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE public.app_settings_seq OWNER TO postgres;

CREATE TABLE public.card_tokens (
                                    id bigint NOT NULL,
                                    client_id uuid NOT NULL,
                                    token text NOT NULL
);

ALTER TABLE public.card_tokens OWNER TO postgres;

CREATE SEQUENCE public.card_tokens_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE public.card_tokens_seq OWNER TO postgres;

CREATE TABLE public.clients (
                                blocked boolean,
                                registration_date timestamp(6) without time zone NOT NULL,
                                id uuid NOT NULL,
                                midname character varying(50),
                                name character varying(50) NOT NULL,
                                surname character varying(50) NOT NULL,
                                phone text NOT NULL,
                                role character varying(255) NOT NULL,
                                CONSTRAINT clients_role_check CHECK (((role)::text = ANY ((ARRAY['ROLE_EMPLOYEE'::character varying, 'ROLE_CLIENT'::character varying, 'ROLE_ADMIN'::character varying])::text[])))
);


ALTER TABLE public.clients OWNER TO postgres;

CREATE TABLE public.employees (
                                  created_at timestamp(6) without time zone NOT NULL,
                                  id bigint NOT NULL,
                                  updated_at timestamp(6) without time zone NOT NULL,
                                  email character varying(50) NOT NULL,
                                  midname character varying(50),
                                  name character varying(50) NOT NULL,
                                  surname character varying(50) NOT NULL,
                                  password character varying(255) NOT NULL,
                                  role character varying(255) NOT NULL,
                                  CONSTRAINT employees_role_check CHECK (((role)::text = ANY ((ARRAY['ROLE_EMPLOYEE'::character varying, 'ROLE_CLIENT'::character varying, 'ROLE_ADMIN'::character varying])::text[])))
);

ALTER TABLE public.employees OWNER TO postgres;

CREATE SEQUENCE public.employees_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.employees_seq OWNER TO postgres;

CREATE TABLE public.flyway_schema_history (
                                              installed_rank integer NOT NULL,
                                              version character varying(50),
                                              description character varying(200) NOT NULL,
                                              type character varying(20) NOT NULL,
                                              script character varying(1000) NOT NULL,
                                              checksum integer,
                                              installed_by character varying(100) NOT NULL,
                                              installed_on timestamp without time zone DEFAULT now() NOT NULL,
                                              execution_time integer NOT NULL,
                                              success boolean NOT NULL
);

ALTER TABLE public.flyway_schema_history OWNER TO postgres;

CREATE TABLE public.registration_codes (
                                           used boolean NOT NULL,
                                           expires_at timestamp(6) without time zone NOT NULL,
                                           id bigint NOT NULL,
                                           code character varying(50) NOT NULL,
                                           email character varying(50) NOT NULL,
                                           role character varying(255) NOT NULL,
                                           CONSTRAINT registration_codes_role_check CHECK (((role)::text = ANY ((ARRAY['ROLE_EMPLOYEE'::character varying, 'ROLE_CLIENT'::character varying, 'ROLE_ADMIN'::character varying])::text[])))
);

ALTER TABLE public.registration_codes OWNER TO postgres;

CREATE SEQUENCE public.registration_codes_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.registration_codes_seq OWNER TO postgres;

CREATE TABLE public.sms_codes (
                                  code character varying(4) NOT NULL,
                                  create_date timestamp(6) without time zone NOT NULL,
                                  expire_time timestamp(6) without time zone,
                                  id bigint NOT NULL,
                                  update_date timestamp(6) without time zone,
                                  phone character varying(255) NOT NULL,
                                  status character varying(255) NOT NULL,
                                  CONSTRAINT sms_codes_status_check CHECK (((status)::text = ANY ((ARRAY['CREATED'::character varying, 'SEND'::character varying, 'VERIFIED'::character varying, 'EXPIRED'::character varying])::text[])))
);


ALTER TABLE public.sms_codes OWNER TO postgres;

CREATE SEQUENCE public.sms_codes_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.sms_codes_seq OWNER TO postgres;

CREATE TABLE public.subscription (
                                     active boolean NOT NULL,
                                     end_time date NOT NULL,
                                     start_time date NOT NULL,
                                     id bigint NOT NULL,
                                     client_id uuid NOT NULL,
                                     subscription_type character varying(255) NOT NULL,
                                     CONSTRAINT subscription_subscription_type_check CHECK (((subscription_type)::text = 'DEFAULT'::text))
);

ALTER TABLE public.subscription OWNER TO postgres;

ALTER TABLE public.subscription ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.subscription_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.transactions (
                                     amount bigint NOT NULL,
                                     card_token_id bigint,
                                     create_date timestamp(6) without time zone NOT NULL,
                                     fee bigint NOT NULL,
                                     fee_percent bigint NOT NULL,
                                     update_date timestamp(6) without time zone,
                                     client_id uuid NOT NULL,
                                     id uuid NOT NULL,
                                     currency character varying(255) NOT NULL,
                                     description character varying(255) NOT NULL,
                                     status text NOT NULL,
                                     CONSTRAINT transactions_currency_check CHECK (((currency)::text = 'RUB'::text)),
    CONSTRAINT transactions_status_check CHECK ((status = ANY (ARRAY['NEW'::text, 'IN_PROGRESS'::text, 'DONE'::text, 'CANCELED'::text, 'REFUNDED'::text])))
);

ALTER TABLE public.transactions OWNER TO postgres;

ALTER TABLE ONLY public.app_settings
    ADD CONSTRAINT app_settings_module_key UNIQUE (module);

ALTER TABLE ONLY public.app_settings
    ADD CONSTRAINT app_settings_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.app_settings
    ADD CONSTRAINT app_settings_setting_key UNIQUE (setting);

ALTER TABLE ONLY public.card_tokens
    ADD CONSTRAINT card_tokens_client_id_key UNIQUE (client_id);

ALTER TABLE ONLY public.card_tokens
    ADD CONSTRAINT card_tokens_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.card_tokens
    ADD CONSTRAINT card_tokens_token_key UNIQUE (token);

ALTER TABLE ONLY public.clients
    ADD CONSTRAINT clients_phone_key UNIQUE (phone);

ALTER TABLE ONLY public.clients
    ADD CONSTRAINT clients_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT employees_email_key UNIQUE (email);

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT employees_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.flyway_schema_history
    ADD CONSTRAINT flyway_schema_history_pk PRIMARY KEY (installed_rank);

ALTER TABLE ONLY public.registration_codes
    ADD CONSTRAINT registration_codes_code_key UNIQUE (code);

ALTER TABLE ONLY public.registration_codes
    ADD CONSTRAINT registration_codes_email_key UNIQUE (email);

ALTER TABLE ONLY public.registration_codes
    ADD CONSTRAINT registration_codes_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.sms_codes
    ADD CONSTRAINT sms_codes_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.subscription
    ADD CONSTRAINT subscription_client_id_key UNIQUE (client_id);

ALTER TABLE ONLY public.subscription
    ADD CONSTRAINT subscription_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT transactions_pkey PRIMARY KEY (id);

CREATE INDEX flyway_schema_history_s_idx ON public.flyway_schema_history USING btree (success);

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT fk1cmqgln21d49plwgufjvl5ios FOREIGN KEY (card_token_id) REFERENCES public.card_tokens(id);

ALTER TABLE ONLY public.card_tokens
    ADD CONSTRAINT fkbvhrjbsot8nwyx0bx41mssdwx FOREIGN KEY (client_id) REFERENCES public.clients(id);

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT fkjp6w7dmqrj0h9vykk2pbtik2 FOREIGN KEY (client_id) REFERENCES public.clients(id);

ALTER TABLE ONLY public.subscription
    ADD CONSTRAINT fkmgdo6ymscw0s5677kyvnwf34w FOREIGN KEY (client_id) REFERENCES public.clients(id);

create sequence app_settings_seq
    increment by 50;

alter sequence app_settings_seq owner to postgres;

create sequence card_tokens_seq
    increment by 50;

alter sequence card_tokens_seq owner to postgres;

create sequence employees_seq
    increment by 50;

alter sequence employees_seq owner to postgres;

create sequence registration_codes_seq
    increment by 50;

alter sequence registration_codes_seq owner to postgres;

create sequence sms_codes_seq
    increment by 50;

alter sequence sms_codes_seq owner to postgres;

create sequence app_settings_id_seq;

alter sequence app_settings_id_seq owner to postgres;

alter sequence app_settings_id_seq owned by app_settings.id;

create sequence subscription_id_seq;

alter sequence subscription_id_seq owner to postgres;

alter sequence subscription_id_seq owned by subscription.id;